name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install APT depenencies
      run: |
        sudo apt-get -y install mosquitto
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Install and pack web ui assets
      run: |
        npm install
        npm run build
    - name: Test with coverage + unittest
      run: |
        coverage run --source=shc,example -m unittest
    - name: Report test coverage
      if: ${{ always() }}
      run: |
        coverage xml
        coverage report -m
    - uses: codecov/codecov-action@v2
      if: ${{ always() }}

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle mypy
        pip install -r requirements.txt
    - name: Check typing with MyPy
      run: |
        mypy shc/ test/ example/
    - name: Check code style with PyCodestyle
      run: |
        pycodestyle --max-line-length 120 shc/ test/ example/

  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Create source and wheel dist
      run: |
        python setup.py sdist bdist_wheel
