name: build

on:
  push:
    branches: [ main, v*.x ]
  pull_request:
    branches: [ main, v*.x ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install APT depenencies
      run: |
        sudo apt-get update
        sudo apt-get -y install mosquitto libpulse0 pulseaudio knxd knxd-tools mariadb-server mariadb-client
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[mysql,knx,dmx,midi,mqtt,pulse,telegram,file_persistence,test]
        pip uninstall -y python-rtmidi  # not working on GitHub actions
    - name: Install and pack web ui assets
      run: |
        npm install
        npm run build
    - name: Setup MySQL test database
      run: |
        sudo mysql << "__EOF__"
          CREATE DATABASE `shc_test`;
          CREATE USER 'shc_test'@'localhost' IDENTIFIED BY 'shc_test';
          GRANT ALL PRIVILEGES ON `shc_test`.* TO  'shc_test'@'localhost';
          FLUSH PRIVILEGES;
        __EOF__
    - name: Test with coverage + unittest
      run: |
        coverage run --source=shc,example -m unittest -v
      env:
        SHC_TEST_MSQL_URL: mysql://shc_test:shc_test@localhost/shc_test
    - name: Report test coverage
      if: ${{ always() }}
      run: |
        coverage xml
        coverage report -m
    - uses: codecov/codecov-action@v4
      if: ${{ always() }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[mysql,knx,dmx,midi,mqtt,pulse,telegram,file_persistence,dev]
    - name: Lint code with ruff
      run: |
        ruff check .

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[mysql,knx,dmx,midi,mqtt,pulse,telegram,file_persistence,test]
    - name: Check typing with MyPy
      run: |
        mypy

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[mysql,knx,dmx,midi,mqtt,pulse,telegram,file_persistence,doc]
    - name: Build HTML docs with Sphinx
      run: |
        cd docs
        sphinx-build -M html . _build
    - name: Archive built package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          docs/_build/html

  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
    - name: Create source and wheel dist
      run: |
        python -m build
    - name: Archive built package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist
